model_id: yolo11n_track
display_name: "YOLO11n Detection with Tracking"
batch_processing_mode: "default"

params:
  model_path: "yolo11n.pt"
  device: "cuda:0"
  tracker_type: "bytetrack"

widgets:
  - name: button_run
    value: null
  - name: input_conf
    value: null
  - name: edit_conf
    value: 0.25
  - name: input_iou
    value: null
  - name: edit_iou
    value: 0.70
  - name: toggle_preserve_existing_annotations
    value: false
  - name: button_reset_tracker
    value: null
