model_id: yolo11s
display_name: "YOLO11s Detection"
batch_processing_mode: "default"

params:
  model_path: "yolo11s.pt"
  device: "cpu"

widgets:
  - name: button_run
    value: null
  - name: input_conf
    value: null
  - name: edit_conf
    value: 0.25
  - name: input_iou
    value: null
  - name: edit_iou
    value: 0.70
  - name: toggle_preserve_existing_annotations
    value: false
